### ISSUE TITLE
How to visualize the attention map in the paper?

### ISSUE THREAD

**Issue by zjusxh** [yangzhou321/VQBasedRepresentationLearning#1]
The author adds a self-attention module in Sec3.3 of the paper. I want to visualize the attention map like Fig. 1. How to do it? Could you share the code?

**Comment by yangzhou321** [comment]
We use the tool “pytorch_grad_cam” to display GradCAM, and you can refer to the code: "gradcam_display.py" and this repository: [pytorch_grad_cam](https://github.com/jacobgil/pytorch-grad-cam) for details.
