### ISSUE TITLE
Code available?

### ISSUE THREAD

**Issue by tjdhg456** [yangzhou321/VQBasedRepresentationLearning#2]
Hello. Thank you for your great work accepted on CVPR 2023.

When will you publicize the official code?

Thank you.

**Comment by yangzhou321** [comment]
Thank you for your reminder. I have organized the code and uploaded it. Please feel free to review it. If you have any questions, don't hesitate to discuss them with me at any time.

**Comment by tjdhg456** [comment]
Thank you for your code and kind reply.
I'll perform experiments based on your research and further discuss with you!

Thank you very much for your inspiring works.
