### ISSUE TITLE
ModuleNotFoundError: No module named 'imagecorruptions'

### ISSUE THREAD

**Issue by waychin-weiqin** [yangzhou321/VQBasedRepresentationLearning#4]
Hi,

Thank you for sharing your work! I am having an issue when trying to reproduce your code. I believe the file for generating corruption for training data is missing from the repo as I am receiving the following error: 

> `ModuleNotFoundError: No module named 'imagecorruptions'. `

It would be great if you could include it in the repo. 

Thank you :)

**Comment by yangzhou321** [comment]
Thank you for your interest in our work. This package is pip installable via `pip install imagecorruptions.` Please refer to  [this issue](https://github.com/yangzhou321/VQSA/issues/3#issuecomment-1788449944) or [imagecorruptions](https://github.com/bethgelab/imagecorruptions) for details.

**Comment by waychin-weiqin** [comment]
Excellent!! Thank you for your swift reply! 😄
